### ISSUE TITLE
Values of Temperature and Precipitation

### ISSUE THREAD

**Issue by coderkhaleesi** [SERVIR/ClimateSERVpy#1]
I know this is not a bug in your code, but I used these params:

GeometryCoords = [[14.6937, -17.44406]]
                  
DatasetType = 'Seasonal_Forecast'
OperationType = 'Min' #Use download here to download the TIF files
EarliestDate = '01/12/2018'
LatestDate = '01/12/2019'
SeasonalEnsemble = 'ens06'
SeasonalVariable = 'Temperature'
Outfile = 'out.csv'

And the values of temperature are around 287-296. I am not sure why that is happening. Please help.

**Comment by coderkhaleesi** [comment]
Okay, I just realized that temp might be in Kelvin. Is that true? Because I can't find units.

**Comment by billyz313** [comment]
Good catch, yes the values are in Kelvin.  Looks like there is room for better documentation on the datasets.

**Comment by coderkhaleesi** [comment]
Thank you, @billyz313.
Yes, true. I will be working with this data. I could create a doc for the same.

**Comment by billyz313** [comment]
We are currently working on a complete rewrite of the entire ClimateSERV system that will be more powerful and efficient.  All of the API calls will be backward compatible and there will be some additional operations enabled,  That being said, they are also updating all of the documentation and I will be sure to request that they add units to the dataset documentation.
