### ISSUE TITLE
CHIRPS_GEFS_precip_75 silently failing?

### ISSUE THREAD

**Issue by mickymags** [SERVIR/ClimateSERVpy#2]
Hello, I am running this code within Google Colab (Python v. 3.7.12) on My Mac (v 12.2.1)

When I attempt to write the CHIRPS_GEFS_Precipitation (75th percentile) data to a CSV file, the script runs without error. 

However, the job progress indicator stays stuck at zero. I have tried restarting runtime, and running the code for over 10 minutes, both with no luck. I was able to use the 25th percentile and mean datasets with no issue, and haven't experienced this issue with any other ClimateSERV datasets. 

Attached is a screenshot of my code and the aforementioned issue
<img width="1632" alt="Screen Shot 2022-02-23 at 4 05 41 PM" src="https://user-images.githubusercontent.com/96547199/155417636-77b2300a-caa1-42d5-ab33-76742a73d44d.png">

**Comment by billyz313** [comment]
It turns out that they stopped producing the 25th nd 75th percentile so they are no longer available.  The mean and anomaly data are both still available.

**Comment by mickymags** [comment]
Weird, because I was able to still get 25th percentile data, just not 75th. 

Thanks!

**Comment by billyz313** [comment]
Thank you for mentioning ur getting the 25th.  The data u received for the 25th turns out to be the mean data not the 25th, it should also fail instead.  This will be updated with the next deployment as well, and they will both fail properly with a -1 progress.
