### ISSUE TITLE
Docs Issue with eMODIS NDVI dataset and CHIRPS-GEFS Anamolies

### ISSUE THREAD

**Issue by mickymags** [SERVIR/ClimateSERVpy#3]
Hello, I'm not sure if this is the best place to post this issue, but there is a small docs issue on the ClimateSERV [help center website.](https://climateserv.servirglobal.net/help) Under the "Developers API" heading, it says the availability of the eMODIS NDVI datasets are pentadal, when they are dekadal according to the [USGS website](https://www.usgs.gov/centers/eros/science/usgs-eros-archive-vegetation-monitoring-eros-moderate-resolution-imaging). Additionally, when we import the data into Python we can see that they are dekadal (See Attached image). 

This issue is present for all of the NDVI datasets on ClimateSERV (Central Asia, Southern Africa, East Africa, West Africa)
<img width="1630" alt="ClimateSERV_NDVI_Issue" src="https://user-images.githubusercontent.com/96547199/155747961-fe351861-689b-443b-b58a-74a09662bac2.png">

Additionally, this page claims that the CHIRPS-GEFS Anomalies data ranges from 1981 to present. While this is true for the CHIRPS precipitation data, it is not true for the CHIRPS-GEFS Anomalies data, which seems to begin on 01/01/2001.

**Comment by billyz313** [comment]
Thank you, I appreciate it.  The documentation corrections will be in the next deployment cycle.  The GEFS Anomalies are the V12 10-day product which actually only goes back to 2020, and will be updated in the docs as well.
