### ISSUE TITLE
Bad Data in CHIRPS-GEFS Anamloy Dataset

### ISSUE THREAD

**Issue by mickymags** [SERVIR/ClimateSERVpy#4]
Hello, when I attempt to import CHIRPS-GEFS Anamoly dataset (Dataset_Type = 'CHIRPS_GEFS_anom') into Python, I get bad data  (-9999.0) for 20 years. October 5, 2020 is the first day that I get usable data. Is this functioning as intended? I've attached a screenshot of my code
<img width="1630" alt="ClimateSERV_GEFS_Issue" src="https://user-images.githubusercontent.com/96547199/155750449-7a4913d0-9976-4c09-a554-10b18bbc9c39.png">
.

**Comment by billyz313** [comment]
The GEFS Anomalies are the UCSB V12 10-day product which actually only goes back to October 5, 2020.  Thank you for bring this to my attention, the documentation will be updated soon.
